services:
  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3360:3306"
    volumes:
      - mysql-database:/var/lib/mysql
    networks:
      - my-network

  todo-service:
    container_name: todo-service
    image: sha256:01e3cf81165c262f5f8ed117727db3dae526dd3477de7ef1d301d271d75d843c
    depends_on:
      - mysql-container
    networks:
      - my-network

volumes:
  mysql-database:
    name: mysql-database

networks:
  my-network:
    name: my-network
    external: true