version: '3.8'

services:
  mysql-container:
    container_name: mysql-container
    image: sha256:680b8c60dce62c25af20deda8764e29191709a4495b116f6b4d655061d3bd8ff
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3360:3306"
    volumes:
      - mysql-database:/var/lib/mysql
    networks:
          - todo-network

  todo-service:
    container_name: todo-service
    image: sha256:b77046c10eb1f41419b8afb558bcebfe129f896fb6a7f295c723127ef8ee78ab
    depends_on:
      - mysql-container
    networks:
      - todo-network

volumes:
  mysql-database:
    name: mysql-database

networks:
  todo-network:
    name: todo-network
    external: true